@echo off
echo Installing UV Python package manager...
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

echo Adding UV to PATH for current session...
set "PATH=%PATH%;%USERPROFILE%\.cargo\bin"

echo Running uv sync...
uv sync

echo Setup complete! Closing in 3 seconds...
timeout /t 3 /nobreak >nul